2023-04-17 16:34:55,681 - speechbrain.core - INFO - Beginning experiment!
2023-04-17 16:34:55,681 - speechbrain.core - INFO - Experiment folder: ./results_hpc/4234-3_1
2023-04-17 16:34:56,994 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
attrs==22.2.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
cmake==3.26.0
distlib==0.3.6
entrypoints==0.3
filelock==3.10.0
flake8==3.7.9
huggingface-hub==0.13.3
HyperPyYAML==1.1.0
identify==2.5.21
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.0
MarkupSafe==2.1.2
mccabe==0.6.1
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.0
nodeenv==1.7.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.0
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==3.2.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.2
scipy==1.8.1
sentencepiece==0.1.97
speechbrain==0.5.14
sympy==1.11.1
threadpoolctl==3.1.0
toml==0.10.2
torch==2.0.0
torchaudio==2.0.1
tqdm==4.65.0
triton==2.0.0
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==1.26.15
virtualenv==20.21.0
wcwidth==0.2.6
yamllint==1.23.0


2023-04-17 16:34:57,033 - speechbrain.utils.superpowers - DEBUG - 1ac2c5d


2023-04-17 16:34:58,046 - data_prepare - INFO - Creating .\\./results_hpc/4234-3_1\\train.json, .\\./results_hpc/4234-3_1\\valid.json, and .\\./results_hpc/4234-3_1\\test.json
2023-04-17 16:34:58,046 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 270, in <module>
    sb.utils.distributed.run_on_main(
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/data_prepare.py", line 29, in data_prepare
    wav_list_train = get_all_files(train_folder, match_and=extension)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_utils.py", line 87, in get_all_files
    listOfFile = os.listdir(dirName)
FileNotFoundError: [Errno 2] No such file or directory: '/$TMPDIR\\corpus-3_1-split/train'
2023-04-17 16:38:33,582 - speechbrain.core - INFO - Beginning experiment!
2023-04-17 16:38:33,583 - speechbrain.core - INFO - Experiment folder: ./results_hpc/4234-3_1
2023-04-17 16:38:34,552 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
attrs==22.2.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
cmake==3.26.0
distlib==0.3.6
entrypoints==0.3
filelock==3.10.0
flake8==3.7.9
huggingface-hub==0.13.3
HyperPyYAML==1.1.0
identify==2.5.21
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.0
MarkupSafe==2.1.2
mccabe==0.6.1
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.0
nodeenv==1.7.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.0
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==3.2.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.2
scipy==1.8.1
sentencepiece==0.1.97
speechbrain==0.5.14
sympy==1.11.1
threadpoolctl==3.1.0
toml==0.10.2
torch==2.0.0
torchaudio==2.0.1
tqdm==4.65.0
triton==2.0.0
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==1.26.15
virtualenv==20.21.0
wcwidth==0.2.6
yamllint==1.23.0


2023-04-17 16:38:34,568 - speechbrain.utils.superpowers - DEBUG - 1ac2c5d


2023-04-17 16:38:35,562 - data_prepare - INFO - Creating .\\./results_hpc/4234-3_1\\train.json, .\\./results_hpc/4234-3_1\\valid.json, and .\\./results_hpc/4234-3_1\\test.json
2023-04-17 16:38:35,563 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 270, in <module>
    sb.utils.distributed.run_on_main(
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/data_prepare.py", line 29, in data_prepare
    wav_list_train = get_all_files(train_folder, match_and=extension)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_utils.py", line 87, in get_all_files
    listOfFile = os.listdir(dirName)
FileNotFoundError: [Errno 2] No such file or directory: '$TMPDIR\\corpus-3_1-split/train'
2023-04-17 16:42:54,226 - speechbrain.core - INFO - Beginning experiment!
2023-04-17 16:42:54,226 - speechbrain.core - INFO - Experiment folder: ./results_hpc/4234-3_1
2023-04-17 16:42:55,146 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
attrs==22.2.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
cmake==3.26.0
distlib==0.3.6
entrypoints==0.3
filelock==3.10.0
flake8==3.7.9
huggingface-hub==0.13.3
HyperPyYAML==1.1.0
identify==2.5.21
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.0
MarkupSafe==2.1.2
mccabe==0.6.1
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.0
nodeenv==1.7.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.0
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==3.2.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.2
scipy==1.8.1
sentencepiece==0.1.97
speechbrain==0.5.14
sympy==1.11.1
threadpoolctl==3.1.0
toml==0.10.2
torch==2.0.0
torchaudio==2.0.1
tqdm==4.65.0
triton==2.0.0
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==1.26.15
virtualenv==20.21.0
wcwidth==0.2.6
yamllint==1.23.0


2023-04-17 16:42:55,162 - speechbrain.utils.superpowers - DEBUG - 1ac2c5d


2023-04-17 16:42:56,146 - data_prepare - INFO - Creating .\\./results_hpc/4234-3_1\\train.json, .\\./results_hpc/4234-3_1\\valid.json, and .\\./results_hpc/4234-3_1\\test.json
2023-04-17 16:42:56,147 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 270, in <module>
    sb.utils.distributed.run_on_main(
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/data_prepare.py", line 29, in data_prepare
    wav_list_train = get_all_files(train_folder, match_and=extension)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_utils.py", line 87, in get_all_files
    listOfFile = os.listdir(dirName)
FileNotFoundError: [Errno 2] No such file or directory: '$TMPDIR\\corpus-3_1-split/train'
2023-04-17 16:46:56,251 - speechbrain.core - INFO - Beginning experiment!
2023-04-17 16:46:56,251 - speechbrain.core - INFO - Experiment folder: ./results_hpc/4234-3_1
2023-04-17 16:46:57,191 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
attrs==22.2.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
cmake==3.26.0
distlib==0.3.6
entrypoints==0.3
filelock==3.10.0
flake8==3.7.9
huggingface-hub==0.13.3
HyperPyYAML==1.1.0
identify==2.5.21
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.0
MarkupSafe==2.1.2
mccabe==0.6.1
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.0
nodeenv==1.7.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.0
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==3.2.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.2
scipy==1.8.1
sentencepiece==0.1.97
speechbrain==0.5.14
sympy==1.11.1
threadpoolctl==3.1.0
toml==0.10.2
torch==2.0.0
torchaudio==2.0.1
tqdm==4.65.0
triton==2.0.0
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==1.26.15
virtualenv==20.21.0
wcwidth==0.2.6
yamllint==1.23.0


2023-04-17 16:46:57,210 - speechbrain.utils.superpowers - DEBUG - 1ac2c5d


2023-04-17 16:46:58,192 - data_prepare - INFO - Creating .\\./results_hpc/4234-3_1\\train.json, .\\./results_hpc/4234-3_1\\valid.json, and .\\./results_hpc/4234-3_1\\test.json
2023-04-17 16:48:08,377 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 270, in <module>
    sb.utils.distributed.run_on_main(
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/data_prepare.py", line 32, in data_prepare
    create_json(wav_list_train, save_json_train)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/data_prepare.py", line 64, in create_json
    with open(json_file, mode="w") as json_f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\\\./results_hpc/4234-3_1\\\\train.json'
2023-04-17 16:52:36,410 - speechbrain.core - INFO - Beginning experiment!
2023-04-17 16:52:36,410 - speechbrain.core - INFO - Experiment folder: ./results_hpc/4234-3_1
2023-04-17 16:52:37,354 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
attrs==22.2.0
black==19.10b0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.0.4
cmake==3.26.0
distlib==0.3.6
entrypoints==0.3
filelock==3.10.0
flake8==3.7.9
huggingface-hub==0.13.3
HyperPyYAML==1.1.0
identify==2.5.21
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.0
MarkupSafe==2.1.2
mccabe==0.6.1
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.0
nodeenv==1.7.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.0
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==3.2.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pytest==5.4.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.2
scipy==1.8.1
sentencepiece==0.1.97
speechbrain==0.5.14
sympy==1.11.1
threadpoolctl==3.1.0
toml==0.10.2
torch==2.0.0
torchaudio==2.0.1
tqdm==4.65.0
triton==2.0.0
typed-ast==1.5.4
typing_extensions==4.5.0
urllib3==1.26.15
virtualenv==20.21.0
wcwidth==0.2.6
yamllint==1.23.0


2023-04-17 16:52:37,369 - speechbrain.utils.superpowers - DEBUG - 1ac2c5d


2023-04-17 16:52:38,354 - data_prepare - INFO - Creating ./results_hpc/4234-3_1\\train.json, ./results_hpc/4234-3_1\\valid.json, and ./results_hpc/4234-3_1\\test.json
2023-04-17 16:53:47,395 - data_prepare - INFO - ./results_hpc/4234-3_1\\train.json successfully created!
2023-04-17 16:53:57,176 - data_prepare - INFO - ./results_hpc/4234-3_1\\valid.json successfully created!
2023-04-17 16:54:16,657 - data_prepare - INFO - ./results_hpc/4234-3_1\\test.json successfully created!
2023-04-17 16:54:27,404 - speechbrain.core - INFO - 3.4M trainable parameters in SEBrain
2023-04-17 16:54:27,407 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-04-17 16:54:27,408 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-04-17 16:54:27,414 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 297, in <module>
    se_brain.fit(
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/core.py", line 1225, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/core.py", line 1073, in _fit_train
    for batch in t:
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/dataio/dataset.py", line 165, in __getitem__
    return self.pipeline.compute_outputs({"id": data_id, **data_point})
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_pipeline.py", line 464, in compute_outputs
    return self._compute(data, self._exec_order, self.output_mapping)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_pipeline.py", line 496, in _compute
    values = item(*args)  # Call the DynamicItem to produce output
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/utils/data_pipeline.py", line 72, in __call__
    return self.func(*args)
  File "/home/acp22hz/Speech_enhancement_team_project/enhancement/train.py", line 226, in audio_pipeline
    clean_sig = sb.dataio.dataio.read_audio(wav.replace(f'corpus-{hparams["dataset_id"]}', 'corpus-0'))
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/speechbrain/dataio/dataio.py", line 217, in read_audio
    audio, _ = torchaudio.load(waveforms_obj)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 256, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/acp22hz/.conda/envs/tp/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 30, in _fail_load
    raise RuntimeError("Failed to load audio from {}".format(filepath))
RuntimeError: Failed to load audio from /scratch/corpus-0-split/train/p275_226.wav
